site_name: Sample Documentation
pages:
- Home: index.md
- Using the DataBase: user-guide/dbinputs.md
- Using the Framework: user-guide/usingtheframework.md
- Accessing DataBase: developers-guide/databaseaccess.md
theme: readthedocs

